services:
  app:
    container_name: minimalist-app
    build: .
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: "serverName=MinimaList"
    networks:
      - minimalist-db-network

  db:
    container_name: minimalist-db
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./.docker-local/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    networks:
      - minimalist-db-network

volumes:
  db_data:
    driver: local
    name: minimalist_db_data

networks:
  minimalist-db-network:
    driver: bridge
    name: minimalist-db-network
